<a href="https://colab.research.google.com/github/Vikram-Ahuja/Machine_Learning_Studies/blob/main/MLTutorial6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [175]:
import tensorflow as tf

In [176]:
##Created Random Tensors
random_tensor1 = tf.random.uniform(shape =(5,2),minval=0,maxval=100,dtype=tf.float64,seed =13)

random_tensor2 =tf.random.normal(shape=(1,1,1,1),mean=50,stddev=10,dtype=tf.float64,seed = 13)

random_tensor2.ndim

4

In [177]:
#Shuffling the tensors

print(random_tensor1)

tf.random.set_seed(13)
random_tensor3 = tf.random.shuffle(random_tensor1,seed=13)

print(random_tensor3)

random_tensor1[0]

tf.Tensor(
[[ 4.3527706  90.5250803 ]
 [ 0.54944547 28.83540087]
 [ 2.20162972 37.34918672]
 [66.577573   31.64387472]
 [72.35766796 17.18058111]], shape=(5, 2), dtype=float64)
tf.Tensor(
[[ 0.54944547 28.83540087]
 [ 4.3527706  90.5250803 ]
 [72.35766796 17.18058111]
 [ 2.20162972 37.34918672]
 [66.577573   31.64387472]], shape=(5, 2), dtype=float64)


<tf.Tensor: shape=(2,), dtype=float64, numpy=array([ 4.3527706, 90.5250803])>

In [178]:
zero_tensor = tf.zeros(shape=(3,12),dtype=tf.float64,name="Zerooooooo")

zero_tensor

<tf.Tensor: shape=(3, 12), dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])>

In [179]:
tf.reshape(tensor=zero_tensor,shape=(6,6))

<tf.Tensor: shape=(6, 6), dtype=float64, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])>

In [180]:
random_tensor = tf.random.normal(shape = (5,5,5),seed = 13 )

print(random_tensor)
random_tensor =tf.expand_dims(random_tensor,axis=0) # Adds the Dimension
random_tensor=tf.squeeze(random_tensor)#removes the dimension 
random_tensor

tf.Tensor(
[[[ 0.93489206 -0.23150997 -0.60077703 -0.50823057  1.1962602 ]
  [-0.32262048 -0.31859142  0.9403484  -0.7649619   0.3917004 ]
  [-0.5219959  -0.18971556  0.07231053  0.99700207 -2.2673013 ]
  [-0.60667336 -0.94174874 -0.08343678  1.3710041   0.5497593 ]
  [-0.95295835  1.0438824   0.9872973   0.66903025  0.19385022]]

 [[-0.27311322  0.9701311   0.9654078   2.4064984   0.59391385]
  [-1.476547   -1.2169393   0.38666278 -0.3371533  -0.96262443]
  [-0.5349628   1.1190351   1.4671897   0.49287644 -0.3606    ]
  [ 1.869302   -0.42454675  0.12942316 -0.9341276   0.83172834]
  [ 0.2531173  -0.6708323  -0.5179121  -0.09647777  1.7431607 ]]

 [[-1.7538766   2.0238423  -1.2496028   0.39953783  0.17407416]
  [ 0.09150598 -1.8865305   0.8237378   0.15466441 -0.2178094 ]
  [-1.2850229  -0.3360551  -2.0663612   0.5730885  -0.65373373]
  [-1.8546122  -1.2689756  -0.21104825 -1.423704   -0.9327639 ]
  [-1.0475117   0.4561674  -1.5184132   0.4763998  -0.16696508]]

 [[-1.3787165   0.64050

<tf.Tensor: shape=(5, 5, 5), dtype=float32, numpy=
array([[[ 0.93489206, -0.23150997, -0.60077703, -0.50823057,
          1.1962602 ],
        [-0.32262048, -0.31859142,  0.9403484 , -0.7649619 ,
          0.3917004 ],
        [-0.5219959 , -0.18971556,  0.07231053,  0.99700207,
         -2.2673013 ],
        [-0.60667336, -0.94174874, -0.08343678,  1.3710041 ,
          0.5497593 ],
        [-0.95295835,  1.0438824 ,  0.9872973 ,  0.66903025,
          0.19385022]],

       [[-0.27311322,  0.9701311 ,  0.9654078 ,  2.4064984 ,
          0.59391385],
        [-1.476547  , -1.2169393 ,  0.38666278, -0.3371533 ,
         -0.96262443],
        [-0.5349628 ,  1.1190351 ,  1.4671897 ,  0.49287644,
         -0.3606    ],
        [ 1.869302  , -0.42454675,  0.12942316, -0.9341276 ,
          0.83172834],
        [ 0.2531173 , -0.6708323 , -0.5179121 , -0.09647777,
          1.7431607 ]],

       [[-1.7538766 ,  2.0238423 , -1.2496028 ,  0.39953783,
          0.17407416],
        [ 0.09150598,

In [181]:
random_tensor4 = tf.random.uniform( shape = (2,2),minval = 0,maxval=12,seed = 13,dtype =tf.float64)
random_tensor5 = tf.random.uniform( shape = (2,2),minval = 0,maxval=12,seed = 13,dtype =tf.float64)
print(random_tensor4,random_tensor5)
print(" ")
print(tf.matmul(random_tensor4,random_tensor5))#Gives the matrix multiplication of the tensors
print("")
print(tf.matmul(tf.transpose(random_tensor4),tf.transpose(random_tensor5)))#Gives the matrix multiplication of the tensors
print("")
print(tf.tensordot(random_tensor4,random_tensor5,axes=2))
print("")
print(tf.tensordot(random_tensor4,random_tensor5,axes=2))

tf.Tensor(
[[ 0.37276995 10.43797981]
 [ 8.55779111 10.64313953]], shape=(2, 2), dtype=float64) tf.Tensor(
[[10.90617664  9.29896142]
 [ 8.6031378   2.80714768]], shape=(2, 2), dtype=float64)
 
tf.Tensor(
[[ 93.86487361  32.76732423]
 [184.89717747 109.45543386]], shape=(2, 2), dtype=float64)

tf.Tensor(
[[ 83.64406434  27.22997475]
 [212.80859536 119.67624313]], shape=(2, 2), dtype=float64)

tf.Tensor(204.62858717159517, shape=(), dtype=float64)

tf.Tensor(204.62858717159517, shape=(), dtype=float64)


In [182]:
print(random_tensor.dtype)

random_tensor= tf.cast(random_tensor,dtype=tf.float16)
print(random_tensor.dtype)


<dtype: 'float32'>
<dtype: 'float16'>


In [183]:
print(random_tensor3)

print("Max ",tf.math.reduce_max(random_tensor3).numpy())
print("Min ",tf.math.reduce_min(random_tensor3).numpy())
print("Mean ",tf.math.reduce_mean(random_tensor3).numpy())
print("Sum ",tf.math.reduce_sum(random_tensor3).numpy())
print("Standard_div ",tf.math.reduce_std(random_tensor3).numpy())
print("Varience ",tf.math.reduce_variance(random_tensor3).numpy())

print(tf.math.scalar_mul(10000,random_tensor3))


tf.Tensor(
[[ 0.54944547 28.83540087]
 [ 4.3527706  90.5250803 ]
 [72.35766796 17.18058111]
 [ 2.20162972 37.34918672]
 [66.577573   31.64387472]], shape=(5, 2), dtype=float64)
Max  90.52508030257442
Min  0.5494454717340114
Mean  35.157321047872806
Sum  351.5732104787281
Standard_div  30.0826664598419
Varience  904.9668213340967
tf.Tensor(
[[  5494.45471734 288354.00870781]
 [ 43527.70600495 905250.80302574]
 [723576.67961912 171805.81107267]
 [ 22016.29718419 373491.86723982]
 [665775.7300266  316438.74718904]], shape=(5, 2), dtype=float64)


In [184]:
print(random_tensor5)
print(tf.argmax(input= random_tensor5,axis=1))
print(random_tensor5[0])

tf.Tensor(
[[10.90617664  9.29896142]
 [ 8.6031378   2.80714768]], shape=(2, 2), dtype=float64)
tf.Tensor([0 0], shape=(2,), dtype=int64)
tf.Tensor([10.90617664  9.29896142], shape=(2,), dtype=float64)


In [185]:
tf.compat.v1.one_hot([1,2,3,4,5],depth=5, on_value="Yes",off_value="NO" )

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'NO', b'Yes', b'NO', b'NO', b'NO'],
       [b'NO', b'NO', b'Yes', b'NO', b'NO'],
       [b'NO', b'NO', b'NO', b'Yes', b'NO'],
       [b'NO', b'NO', b'NO', b'NO', b'Yes'],
       [b'NO', b'NO', b'NO', b'NO', b'NO']], dtype=object)>